//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("SoftThorn.Monstercat.Browser")]
[assembly: AssemblyCopyright("© 2022 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]23.04.2022 08:43:02")]
[assembly: AssemblyMetadata("Branch", "main")]
[assembly: AssemblyMetadata("Commit", "cd41e8a002e2d6acd64c4b440b00245aa211a1ff")]
[assembly: AssemblyMetadata("Version", "0.1.2-gcd41e8a002")]
