//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("SoftThorn.Monstercat.Browser")]
[assembly: AssemblyCopyright("© 2022 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]24.04.2022 09:44:27")]
[assembly: AssemblyMetadata("Branch", "main")]
[assembly: AssemblyMetadata("Commit", "8dc2bd64c029af2f375d85fd062ed563907fc9f9")]
[assembly: AssemblyMetadata("Version", "0.1.6-g8dc2bd64c0")]
