//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("SoftThorn.Monstercat.Browser")]
[assembly: AssemblyCopyright("© 2023 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]07.01.2023 10:41:00")]
[assembly: AssemblyMetadata("Branch", "development/wpf")]
[assembly: AssemblyMetadata("Commit", "fa6132c46a0edaa7e0ca180a5c22fffbb9fa64d7")]
[assembly: AssemblyMetadata("Version", "1.0.46-gfa6132c46a")]
